Repository SimplifyERP/StartInsights, pull requests merged in 2024-02, with the labels that each got.

#1 feat:pitch craft assign to customizations
  startinsights/start_insights/doctype/pitch_craft/pitch_craft.js
  startinsights/start_insights/doctype/pitch_craft/pitch_craft.json
  startinsights/start_insights/doctype/pitch_craft/pitch_craft.py
  startinsights/start_insights/doctype/pitch_craft_assign/pitch_craft_assign.json
Labels: enhancement

#3 bug-fix:pitch craft all functions of api added image url
  startinsights/website_api/pitch_craft.py
Labels: bug

#5 bug-fix:pitch craft api documents
  startinsights/website_api/pitch_craft.py
Labels: bug

#6 feature:book an expert table status added
  startinsights/start_insights/doctype/book_an_expert/book_an_expert.js
  startinsights/start_insights/doctype/book_an_expert_table/book_an_expert_table.json
  startinsights/website_api/service_list.py
Labels: enhancement

#7 feat:book an expert table status added in dict
  startinsights/website_api/book_an_expert.py
Labels: enhancement

#9 bug-fix:book an expert table
  startinsights/website_api/book_an_expert.py
Labels: bug

#10 feature:Angel Investing video changes
  startinsights/website_api/angel_investing.py
Labels: enhancement

#12 bug-fix:investment deals company logo url added
  startinsights/website_api/investment_deals.py
Labels: bug

#13 bug:investment deals api added get_url function
  startinsights/website_api/investment_deals.py
Labels: bug

#14 feat:pitch craft new added api
  startinsights/start_insights/doctype/pitch_craft/pitch_craft.json
  startinsights/website_api/pitch_craft.py
Labels: enhancement

#15 feature:changes in investment deals
  startinsights/start_insights/doctype/investment_deals/investment_deals.json
  startinsights/start_insights/doctype/investment_team/investment_team.json
  startinsights/website_api/investment_deals.py
Labels: enhancement

#16 feature:new api creation for round wise overview and investor wise ov…
  startinsights/start_insights/doctype/invested_round/__init__.py
  startinsights/start_insights/doctype/invested_round/invested_round.js
  startinsights/start_insights/doctype/invested_round/invested_round.json
  startinsights/start_insights/doctype/invested_round/invested_round.py
  startinsights/start_insights/doctype/invested_round/test_invested_round.py
  startinsights/start_insights/doctype/investor_wise_overview/__init__.py
  startinsights/start_insights/doctype/investor_wise_overview/investor_wise_overview.js
  startinsights/start_insights/doctype/investor_wise_overview/investor_wise_overview.json
  startinsights/start_insights/doctype/investor_wise_overview/investor_wise_overview.py
  startinsights/start_insights/doctype/investor_wise_overview/test_investor_wise_overview.py
  startinsights/start_insights/doctype/round_type/__init__.py
  startinsights/start_insights/doctype/round_type/round_type.js
  startinsights/start_insights/doctype/round_type/round_type.json
  startinsights/start_insights/doctype/round_type/round_type.py
  startinsights/start_insights/doctype/round_type/test_round_type.py
  startinsights/start_insights/doctype/round_wise_overview/__init__.py
  startinsights/start_insights/doctype/round_wise_overview/round_wise_overview.js
  startinsights/start_insights/doctype/round_wise_overview/round_wise_overview.json
  startinsights/start_insights/doctype/round_wise_overview/round_wise_overview.py
  startinsights/start_insights/doctype/round_wise_overview/test_round_wise_overview.py
  startinsights/start_insights/doctype/tag_name/__init__.py
  startinsights/start_insights/doctype/tag_name/tag_name.js
  startinsights/start_insights/doctype/tag_name/tag_name.json
  startinsights/start_insights/doctype/tag_name/tag_name.py
  startinsights/start_insights/doctype/tag_name/test_tag_name.py
  startinsights/website_api/investor_wise_overview.py
  startinsights/website_api/round_wise_overview.py
Labels: enhancement

#17 feat:service listing new args added
  startinsights/hooks.py
  startinsights/override/course_lesson.py
  startinsights/public/js/course_lesson.js
  startinsights/start_insights/custom/course_lesson.json
  startinsights/start_insights/custom/lms_quiz.json
  startinsights/start_insights/doctype/quiz_table/__init__.py
  startinsights/start_insights/doctype/quiz_table/quiz_table.json
  startinsights/start_insights/doctype/quiz_table/quiz_table.py
  startinsights/start_insights/doctype/service_listing/service_listing.json
  startinsights/website_api/quiz.py
  startinsights/website_api/service_list.py
Labels: enhancement

#19 feat:pitch craft payment
  startinsights/start_insights/doctype/book_an_expert/book_an_expert.json
  startinsights/start_insights/doctype/pitch_craft/pitch_craft.json
  startinsights/start_insights/doctype/pitch_craft_payment/__init__.py
  startinsights/start_insights/doctype/pitch_craft_payment/pitch_craft_payment.js
  startinsights/start_insights/doctype/pitch_craft_payment/pitch_craft_payment.json
  startinsights/start_insights/doctype/pitch_craft_payment/pitch_craft_payment.py
  startinsights/start_insights/doctype/pitch_craft_payment/test_pitch_craft_payment.py
  startinsights/website_api/pitch_craft.py
Labels: enhancement

#20 feat:book an expert child table status
  startinsights/website_api/book_an_expert.py
Labels: enhancement

#21 Feat book an expert status
  startinsights/website_api/book_an_expert.py
Labels: enhancement

#24 Feat lms certificate
  startinsights/start_insights/doctype/book_an_expert/book_an_expert.json
  startinsights/start_insights/doctype/investor_wise_overview/investor_wise_overview.json
  startinsights/website_api/book_an_expert.py
  startinsights/website_api/investor_wise_overview.py
  startinsights/website_api/lms_certificate.py
  startinsights/website_api/round_wise_overview.py
Labels: enhancement

#23 feature:linkedin field remove
  startinsights/start_insights/doctype/book_an_expert/book_an_expert.json
  startinsights/start_insights/doctype/investor_wise_overview/investor_wise_overview.json
  startinsights/website_api/book_an_expert.py
  startinsights/website_api/investor_wise_overview.py
  startinsights/website_api/round_wise_overview.py
Labels: enhancement

#27 feature:notification mail for book an expert
  startinsights/start_insights/notification/__init__.py
  startinsights/start_insights/notification/booking_confirmation_mail/__init__.py
  startinsights/start_insights/notification/booking_confirmation_mail/booking_confirmation_mail.json
  startinsights/start_insights/notification/booking_confirmation_mail/booking_confirmation_mail.md
  startinsights/start_insights/notification/booking_confirmation_mail/booking_confirmation_mail.py
Labels: enhancement

#28 bug-fix:startup deals list id added
  startinsights/website_api/startup_deals.py
Labels: bug

#29 bug-fix:pitch craft email send format remove
  startinsights/website_api/pitch_craft.py
Labels: bug

#30 feat:lms certificate pdf
  startinsights/start_insights/custom/lms_certificate.json
  startinsights/start_insights/doctype/lms_email_settings/__init__.py
  startinsights/start_insights/doctype/lms_email_settings/lms_email_settings.js
  startinsights/start_insights/doctype/lms_email_settings/lms_email_settings.json
  startinsights/start_insights/doctype/lms_email_settings/lms_email_settings.py
  startinsights/start_insights/doctype/lms_email_settings/test_lms_email_settings.py
  startinsights/website_api/lms_certificate.py
Labels: enhancement

#31 feature:course lesson custom field added
  startinsights/start_insights/custom/course_lesson.json
  startinsights/start_insights/custom/lms_certificate.json
  startinsights/website_api/lms_course.py
Labels: enhancement

#32 bug-fix:pitch room list and separate id
  startinsights/start_insights/doctype/pitch_room/pitch_room.json
  startinsights/website_api/pitch_room.py
Labels: bug

#33 feat:create pitch added file list
  startinsights/start_insights/doctype/pitch_room/pitch_room.json
  startinsights/website_api/pitch_room.py
Labels: enhancement

#34 feature:pitch room customize
  startinsights/start_insights/doctype/pitch_room/pitch_room.json
  startinsights/website_api/pitch_room.py
Labels: good first issue

#35 feat:pitch room date field added
  startinsights/start_insights/doctype/pitch_room/pitch_room.json
  startinsights/website_api/pitch_room.py
Labels: enhancement

#37 bug-fix:pitch room doc type changed
  startinsights/website_api/pitch_room.py
Labels: bug

#38 bug-fix:pitch room fields changes
  startinsights/start_insights/doctype/pitch_room/pitch_room.json
Labels: bug

#39 bug-fix:service list email path removed
  startinsights/website_api/service_list.py
Labels: bug

#42 bugfix:investors graph wise
  startinsights/website_api/investor_wise_overview.py
Labels: bug

#40 feature:investment_deals_attachment_fields_added
  startinsights/start_insights/doctype/investment_deals/investment_deals.json
  startinsights/start_insights/doctype/investment_deals_document/__init__.py
  startinsights/start_insights/doctype/investment_deals_document/investment_deals_document.json
  startinsights/start_insights/doctype/investment_deals_document/investment_deals_document.py
  startinsights/start_insights/doctype/investment_team/investment_team.json
  startinsights/website_api/investment_deals.py
Labels: enhancement

#43 feat:investor and round wise api changes
  startinsights/start_insights/doctype/investor_wise_overview/investor_wise_overview.json
  startinsights/website_api/investor_wise_overview.py
  startinsights/website_api/round_wise_overview.py
Labels: enhancement

#44 feat:investor round list graph api
  startinsights/website_api/investor_round_wise_graph.py
  startinsights/website_api/investor_wise_overview.py
  startinsights/website_api/round_wise_overview.py
Labels: enhancement

#45 bug-fix:investor and round wise list & Graph
  startinsights/website_api/investor_round_wise_graph.py
Labels: bug

#46 feature:login role added
  startinsights/website_api/login.py
Labels: enhancement

#47 feat:new changes in api
  startinsights/start_insights/doctype/pitch_craft_documents_application/__init__.py
  startinsights/start_insights/doctype/pitch_craft_documents_application/pitch_craft_documents_application.js
  startinsights/start_insights/doctype/pitch_craft_documents_application/pitch_craft_documents_application.json
  startinsights/start_insights/doctype/pitch_craft_documents_application/pitch_craft_documents_application.py
  startinsights/start_insights/doctype/pitch_craft_documents_application/test_pitch_craft_documents_application.py
  startinsights/start_insights/doctype/pitch_craft_payment/pitch_craft_payment.json
  startinsights/start_insights/doctype/profile_application/__init__.py
  startinsights/start_insights/doctype/profile_application/profile_application.js
  startinsights/start_insights/doctype/profile_application/profile_application.json
  startinsights/start_insights/doctype/profile_application/profile_application.py
  startinsights/start_insights/doctype/profile_application/test_profile_application.py
  startinsights/start_insights/doctype/service_listing/service_listing.json
  startinsights/website_api/pitch_craft.py
  startinsights/website_api/profile.py
  startinsights/website_api/service_list.py
Labels: enhancement

#48 feat:investor and round wise doctype read only removed
  startinsights/start_insights/doctype/investor_wise_overview/investor_wise_overview.json
  startinsights/start_insights/doctype/round_wise_overview/round_wise_overview.json
Labels: enhancement

#50 bug-fix:round wise fields
  startinsights/start_insights/doctype/round_wise_overview/round_wise_overview.json
Labels: bug

#52 feat:service listing changes
  startinsights/website_api/service_list.py
Labels: enhancement

#53 feat:profile and login changes in api
  startinsights/start_insights/doctype/login_type/__init__.py
  startinsights/start_insights/doctype/login_type/login_type.js
  startinsights/start_insights/doctype/login_type/login_type.json
  startinsights/start_insights/doctype/login_type/login_type.py
  startinsights/start_insights/doctype/login_type/test_login_type.py
  startinsights/start_insights/doctype/pitch_craft/pitch_craft.js
  startinsights/start_insights/doctype/pitch_craft/pitch_craft.json
  startinsights/start_insights/doctype/pitch_craft_payment/pitch_craft_payment.json
  startinsights/start_insights/doctype/profile_application/profile_application.json
  startinsights/start_insights/doctype/start_insight_user/start_insight_user.py
  startinsights/website_api/login.py
  startinsights/website_api/profile.py
  startinsights/website_api/register.py
Labels: enhancement

#54 feat:startup deals redeem code changes
  startinsights/start_insights/doctype/startup_deals/startup_deals.json
  startinsights/website_api/startup_deals.py
Labels: enhancement

#55 feat:redeem user doctype created
  startinsights/start_insights/doctype/startup_deal_redeem_user/__init__.py
  startinsights/start_insights/doctype/startup_deal_redeem_user/startup_deal_redeem_user.js
  startinsights/start_insights/doctype/startup_deal_redeem_user/startup_deal_redeem_user.json
  startinsights/start_insights/doctype/startup_deal_redeem_user/startup_deal_redeem_user.py
  startinsights/start_insights/doctype/startup_deal_redeem_user/test_startup_deal_redeem_user.py
  startinsights/start_insights/doctype/startup_deals/startup_deals.json
  startinsights/website_api/startup_deals.py
Labels: enhancement

#56 feature:captable management doctype created
  startinsights/start_insights/doctype/captable_management/__init__.py
  startinsights/start_insights/doctype/captable_management/captable_management.js
  startinsights/start_insights/doctype/captable_management/captable_management.json
  startinsights/start_insights/doctype/captable_management/captable_management.py
  startinsights/start_insights/doctype/captable_management/test_captable_management.py
  startinsights/start_insights/doctype/pitch_craft_document_table/__init__.py
  startinsights/start_insights/doctype/pitch_craft_document_table/pitch_craft_document_table.json
  startinsights/start_insights/doctype/pitch_craft_document_table/pitch_craft_document_table.py
  startinsights/start_insights/doctype/pitch_craft_documents_application/pitch_craft_documents_application.json
  startinsights/website_api/investment_deals.py
  startinsights/website_api/pitch_craft.py
Labels: enhancement

#58 bug-fix:pitch craft get domain path fixed
  startinsights/website_api/pitch_craft.py
Labels: bug

#59 feature: url change for all function
  startinsights/website_api/angel_investing.py
  startinsights/website_api/book_an_expert.py
  startinsights/website_api/investment_deals.py
  startinsights/website_api/lms_course.py
  startinsights/website_api/login.py
  startinsights/website_api/pitch_room.py
  startinsights/website_api/pitchdo.py
  startinsights/website_api/startup_deals.py
Labels: duplicate, enhancement

#60 feat:profile api changes
  startinsights/website_api/profile.py
Labels: enhancement

#61 feat:profile update
  startinsights/website_api/profile.py
Labels: enhancement

#62 bug-fix:profile api return name changed
  startinsights/website_api/profile.py
Labels: bug

#63 feature:lms course customer group added
  startinsights/start_insights/custom/lms_course.json
  startinsights/website_api/lms_course.py
Labels: enhancement

#65 feature : book an expert current time calculation added
  startinsights/website_api/book_an_expert.py
Labels: enhancement

#66 feat:captable management api
  startinsights/start_insights/doctype/captable_management/captable_management.json
  startinsights/start_insights/doctype/name_of_the_round/__init__.py
  startinsights/start_insights/doctype/name_of_the_round/name_of_the_round.js
  startinsights/start_insights/doctype/name_of_the_round/name_of_the_round.json
  startinsights/start_insights/doctype/name_of_the_round/name_of_the_round.py
  startinsights/start_insights/doctype/name_of_the_round/test_name_of_the_round.py
  startinsights/start_insights/doctype/profile_application/profile_application.json
  startinsights/website_api/captable_management.py
  startinsights/website_api/investment_deals.py
  startinsights/website_api/login_password.py
  startinsights/website_api/pitch_room.py
Labels: enhancement

#67 feat:search investors list api
  startinsights/start_insights/doctype/firm_type_of_investors/__init__.py
  startinsights/start_insights/doctype/firm_type_of_investors/firm_type_of_investors.js
  startinsights/start_insights/doctype/firm_type_of_investors/firm_type_of_investors.json
  startinsights/start_insights/doctype/firm_type_of_investors/firm_type_of_investors.py
  startinsights/start_insights/doctype/firm_type_of_investors/test_firm_type_of_investors.py
  startinsights/start_insights/doctype/funding_stages/__init__.py
  startinsights/start_insights/doctype/funding_stages/funding_stages.js
  startinsights/start_insights/doctype/funding_stages/funding_stages.json
  startinsights/start_insights/doctype/funding_stages/funding_stages.py
  startinsights/start_insights/doctype/funding_stages/test_funding_stages.py
  startinsights/start_insights/doctype/investor_funding_stages/__init__.py
  startinsights/start_insights/doctype/investor_funding_stages/investor_funding_stages.json
  startinsights/start_insights/doctype/investor_funding_stages/investor_funding_stages.py
  startinsights/start_insights/doctype/search_investors/__init__.py
  startinsights/start_insights/doctype/search_investors/search_investors.js
  startinsights/start_insights/doctype/search_investors/search_investors.json
  startinsights/start_insights/doctype/search_investors/search_investors.py
  startinsights/start_insights/doctype/search_investors/test_search_investors.py
  startinsights/start_insights/doctype/target_countries/__init__.py
  startinsights/start_insights/doctype/target_countries/target_countries.json
  startinsights/start_insights/doctype/target_countries/target_countries.py
  startinsights/start_insights/doctype/user_created_investors/__init__.py
  startinsights/start_insights/doctype/user_created_investors/test_user_created_investors.py
  startinsights/start_insights/doctype/user_created_investors/user_created_investors.js
  startinsights/start_insights/doctype/user_created_investors/user_created_investors.json
  startinsights/start_insights/doctype/user_created_investors/user_created_investors.py
  startinsights/website_api/pitch_room.py
  startinsights/website_api/search_investors.py
Labels: enhancement

#68 bug-fix:search investors image url
  startinsights/website_api/search_investors.py
Labels: bug

#69 bug-fix:image url investors
  startinsights/website_api/search_investors.py
Labels: bug

#70 feat:masters and investors
  startinsights/start_insights/doctype/funding_stages/funding_stages.json
  startinsights/start_insights/doctype/investor_wise_overview/__init__.py
  startinsights/start_insights/doctype/investor_wise_overview/investor_wise_overview.js
  startinsights/start_insights/doctype/investor_wise_overview/investor_wise_overview.json
  startinsights/start_insights/doctype/investor_wise_overview/investor_wise_overview.py
  startinsights/start_insights/doctype/investor_wise_overview/test_investor_wise_overview.py
  startinsights/start_insights/doctype/tag_name/tag_name.json
  startinsights/start_insights/doctype/user_created_investors/user_created_investors.json
  startinsights/website_api/captable_management.py
  startinsights/website_api/investor_round_wise_graph.py
  startinsights/website_api/investor_wise_overview.py
  startinsights/website_api/masters.py
  startinsights/website_api/round_wise_overview.py
  startinsights/website_api/user_creation_investor.py
Labels: enhancement

#71 bug-fix:masters api fixing
  startinsights/website_api/masters.py
Labels: bug

#72 feat:masters api arranged in single api
  startinsights/website_api/masters.py
Labels: enhancement

#73 feat:masters api key name changed
  startinsights/website_api/masters.py
Labels: enhancement
