Repository SimplifyERP/StartInsights, pull requests merged in 2024-03, with the labels that each got.

#74 feature :pitcraft payment details
  startinsights/website_api/pitch_craft.py
Labels: enhancement

#75 feature: customer document created while create user
  startinsights/start_insights/doctype/type_of_plan/__init__.py
  startinsights/start_insights/doctype/type_of_plan/test_type_of_plan.py
  startinsights/start_insights/doctype/type_of_plan/type_of_plan.js
  startinsights/start_insights/doctype/type_of_plan/type_of_plan.json
  startinsights/start_insights/doctype/type_of_plan/type_of_plan.py
  startinsights/website_api/register.py
Labels: enhancement

#77 feature: custom fields added in customer
  startinsights/start_insights/custom/customer.json
Labels: enhancement

#78 feature:profile application save customer document created
  startinsights/start_insights/doctype/profile_application/profile_application.py
Labels: enhancement

#79 feat:corrections and changes in api's
  startinsights/start_insights/doctype/dashboard_banner/dashboard_banner.json
  startinsights/start_insights/doctype/pitch_craft/pitch_craft.json
  startinsights/start_insights/doctype/pitch_craft_payment/pitch_craft_payment.json
  startinsights/website_api/banner_api.py
  startinsights/website_api/pitch_craft.py
Labels: enhancement

#80 feature:Disabled fields added in all parent doctype
  startinsights/start_insights/doctype/book_an_expert/book_an_expert.json
  startinsights/start_insights/doctype/captable_management/captable_management.json
  startinsights/start_insights/doctype/designation/designation.json
  startinsights/start_insights/doctype/document_confirmation/document_confirmation.json
  startinsights/start_insights/doctype/firm_type_of_investors/firm_type_of_investors.json
  startinsights/start_insights/doctype/invested_round/invested_round.json
  startinsights/start_insights/doctype/investment_deals/investment_deals.json
  startinsights/start_insights/doctype/investor_funding_stages/investor_funding_stages.json
  startinsights/start_insights/doctype/lms_email_settings/lms_email_settings.json
  startinsights/start_insights/doctype/name_of_the_round/name_of_the_round.json
  startinsights/start_insights/doctype/pitch_craft_assign/pitch_craft_assign.json
  startinsights/start_insights/doctype/pitch_craft_documents_application/pitch_craft_documents_application.json
  startinsights/start_insights/doctype/pitch_craft_payment/pitch_craft_payment.json
  startinsights/start_insights/doctype/pitch_craft_service_list/pitch_craft_service_list.json
  startinsights/start_insights/doctype/pitch_do/pitch_do.json
  startinsights/start_insights/doctype/pitch_room/pitch_room.json
  startinsights/start_insights/doctype/profile_application/profile_application.json
  startinsights/start_insights/doctype/quiz_chapter/quiz_chapter.json
  startinsights/start_insights/doctype/quiz_question/quiz_question.json
  startinsights/start_insights/doctype/round_type/round_type.json
  startinsights/start_insights/doctype/round_wise_overview/round_wise_overview.json
  startinsights/start_insights/doctype/service_listing/service_listing.json
  startinsights/start_insights/doctype/service_module/service_module.json
  startinsights/start_insights/doctype/startup_deal_redeem_user/startup_deal_redeem_user.json
  startinsights/start_insights/doctype/startup_deals/startup_deals.json
  startinsights/start_insights/doctype/tag_name/tag_name.json
  startinsights/start_insights/doctype/target_countries/target_countries.json
  startinsights/start_insights/doctype/type_of_plan/type_of_plan.json
Labels: enhancement

#81 feat:register page api correction
  startinsights/start_insights/custom/customer.json
  startinsights/start_insights/custom/lead.json
  startinsights/start_insights/doctype/profile_application/profile_application.json
  startinsights/start_insights/doctype/profile_application/profile_application.py
  startinsights/website_api/lms_certificate.py
  startinsights/website_api/pitch_craft.py
  startinsights/website_api/register.py
Labels: enhancement

#82 feat:search investors api page count
  startinsights/website_api/search_investors.py
Labels: enhancement

#83 bug-fix:search investors api str to int
  startinsights/website_api/search_investors.py
Labels: bug

#84 feat:api corrections in search investors
  startinsights/website_api/search_investors.py
Labels: enhancement

#85 feat:serach investors changes in calculate correction
  startinsights/website_api/search_investors.py
Labels: enhancement

#86 feat:register api changes
  startinsights/website_api/register.py
Labels: enhancement

#87 feat:register api given return user details
  startinsights/website_api/register.py
Labels: enhancement

#88 Bug fix register local variable
  startinsights/website_api/register.py
Labels: bug

#89 bug-fix:register api return status fixed
  startinsights/website_api/register.py
Labels: bug

#90 feat:funding crm new created
  startinsights/start_insights/doctype/funding_crm/__init__.py
  startinsights/start_insights/doctype/funding_crm/funding_crm.js
  startinsights/start_insights/doctype/funding_crm/funding_crm.json
  startinsights/start_insights/doctype/funding_crm/funding_crm.py
  startinsights/start_insights/doctype/funding_crm/test_funding_crm.py
  startinsights/start_insights/doctype/search_investors/search_investors.json
  startinsights/start_insights/doctype/search_investors_favourites/__init__.py
  startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.js
  startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.json
  startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.py
  startinsights/start_insights/doctype/search_investors_favourites/test_search_investors_favourites.py
  startinsights/start_insights/doctype/user_created_investors/user_created_investors.json
  startinsights/start_insights/doctype/user_created_investors/user_created_investors.py
  startinsights/website_api/funding_crm.py
  startinsights/website_api/search_investors.py
  startinsights/website_api/user_creation_investor.py
Labels: enhancement

#91 bug-fix:funding crm array and count added for overall
  startinsights/website_api/funding_crm.py
  startinsights/website_api/user_creation_investor.py
Labels: bug

#93 feat:funding crm and search investors
  startinsights/start_insights/doctype/funding_crm/funding_crm.json
  startinsights/start_insights/doctype/search_investors/search_investors.json
  startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.json
  startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.py
  startinsights/website_api/funding_crm.py
  startinsights/website_api/search_investors.py
  startinsights/website_api/user_creation_investor.py
Labels: enhancement

#94 bug-fix:search investors favourites class file corrections
  startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.py
Labels: bug

#96 feat:search investors filter corrected and changed
  startinsights/start_insights/doctype/search_investors/search_investors.json
  startinsights/website_api/search_investors.py
Labels: enhancement

#97 bug-fix:search investors funding stage empty list added
  startinsights/website_api/search_investors.py
Labels: bug

#98 Feat investor application
  startinsights/start_insights/doctype/investor_application/__init__.py
  startinsights/start_insights/doctype/investor_application/investor_application.js
  startinsights/start_insights/doctype/investor_application/investor_application.json
  startinsights/start_insights/doctype/investor_application/investor_application.py
  startinsights/start_insights/doctype/investor_application/test_investor_application.py
Labels: duplicate

#99 bug-fix:search investors favourites get list
  startinsights/website_api/search_investors.py
Labels: bug

#100 bug-fix:funding crm update status method changes
  startinsights/website_api/funding_crm.py
Labels: bug

#101 feature: investor application email send
  startinsights/start_insights/doctype/investor_application/investor_application.js
  startinsights/start_insights/doctype/investor_application/investor_application.py
Labels: enhancement

#102 feat:register api corrections
  startinsights/start_insights/doctype/profile_application/profile_application.py
  startinsights/website_api/register.py
Labels: enhancement

#105 feat:pitch room doctype changes
  startinsights/start_insights/doctype/pitch_room/pitch_room.json
  startinsights/start_insights/doctype/pitch_room_documents_upload/__init__.py
  startinsights/start_insights/doctype/pitch_room_documents_upload/pitch_room_documents_upload.json
  startinsights/start_insights/doctype/pitch_room_documents_upload/pitch_room_documents_upload.py
  startinsights/website_api/pitch_craft.py
  startinsights/website_api/pitch_room.py
Labels: enhancement

#107 feat:service api changes and corrections
  startinsights/start_insights/doctype/my_services/__init__.py
  startinsights/start_insights/doctype/my_services/my_services.js
  startinsights/start_insights/doctype/my_services/my_services.json
  startinsights/start_insights/doctype/my_services/my_services.py
  startinsights/start_insights/doctype/my_services/test_my_services.py
  startinsights/start_insights/doctype/pitch_craft_assign/pitch_craft_assign.json
  startinsights/start_insights/doctype/pitch_craft_documents_application/pitch_craft_documents_application.json
  startinsights/start_insights/doctype/service_documents/__init__.py
  startinsights/start_insights/doctype/service_documents/service_documents.json
  startinsights/start_insights/doctype/service_documents/service_documents.py
  startinsights/start_insights/doctype/service_list/__init__.py
  startinsights/start_insights/doctype/service_list/service_list.js
  startinsights/start_insights/doctype/service_list/service_list.json
  startinsights/start_insights/doctype/service_list/service_list.py
  startinsights/start_insights/doctype/service_list/test_service_list.py
  startinsights/start_insights/doctype/service_payment/__init__.py
  startinsights/start_insights/doctype/service_payment/service_payment.js
  startinsights/start_insights/doctype/service_payment/service_payment.json
  startinsights/start_insights/doctype/service_payment/service_payment.py
  startinsights/start_insights/doctype/service_payment/test_service_payment.py
  startinsights/start_insights/doctype/service_trackings/__init__.py
  startinsights/start_insights/doctype/service_trackings/service_trackings.json
  startinsights/start_insights/doctype/service_trackings/service_trackings.py
  startinsights/start_insights/doctype/services/__init__.py
  startinsights/start_insights/doctype/services/services.js
  startinsights/start_insights/doctype/services/services.json
  startinsights/start_insights/doctype/services/services.py
  startinsights/start_insights/doctype/services/test_services.py
  startinsights/website_api/pitch_craft.py
  startinsights/website_api/profile.py
  startinsights/website_api/services.py
Labels: enhancement

#106 feature:document upload for pitch_room
  startinsights/start_insights/doctype/pitch_room/pitch_room.json
  startinsights/website_api/pitch_room.py
Labels: enhancement

#108 feature:document upload for child table pitch room correction
  startinsights/website_api/pitch_room.py
Labels: enhancement

#109 bug-fix:recommended search investors
  startinsights/start_insights/doctype/search_investors/search_investors.json
  startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.py
  startinsights/website_api/search_investors.py
Labels: bug

#110 feature: auth code send for profile application and email send and ge…
  startinsights/start_insights/doctype/profile_application/profile_application.json
  startinsights/website_api/forget_api.py
Labels: enhancement

#111 bug-fix:forget api reset password fix
  startinsights/start_insights/doctype/profile_application/profile_application.json
  startinsights/website_api/forget_api.py
Labels: bug

#112 bug-fix:api auth code
  startinsights/website_api/forget_api.py
Labels: bug

#116 feat:my services api corrections
  startinsights/start_insights/doctype/my_services/my_services.json
  startinsights/start_insights/doctype/services/services.json
  startinsights/website_api/pitch_room.py
  startinsights/website_api/services.py
Labels: enhancement

#118 bug-fix:my services corrections
  startinsights/website_api/pitch_room.py
  startinsights/website_api/services.py
Labels: bug

#119 feat:my services status added
  startinsights/website_api/services.py
Labels: enhancement

#122 bug-fix:login api null values become empty
  startinsights/website_api/login.py
Labels: bug

#121 feature:pitch room shared user added in child table
  startinsights/start_insights/doctype/pitch_room/pitch_room.json
  startinsights/start_insights/doctype/shared_users/__init__.py
  startinsights/start_insights/doctype/shared_users/shared_users.json
  startinsights/start_insights/doctype/shared_users/shared_users.py
  startinsights/website_api/pitch_room.py
Labels: enhancement

#123 feat:pitch room api corrections
  startinsights/start_insights/doctype/pitch_room/pitch_room.json
  startinsights/website_api/pitch_room.py
  startinsights/website_api/services.py
Labels: enhancement

#124 bug-fix:pitch room get details
  startinsights/website_api/pitch_room.py
Labels: bug

#125 bug-fix:deals api issues fixed
  startinsights/start_insights/doctype/startup_deals/startup_deals.json
  startinsights/website_api/startup_deals.py
Labels: bug

#126 feat:pitch room list api method moved
  startinsights/website_api/pitch_room.py
Labels: enhancement

#127 old-feat:pitch room get user role details
  startinsights/website_api/pitch_room.py
Labels: enhancement

#128 bug-fix:old feature corrections
  startinsights/website_api/pitch_room.py
Labels: enhancement

#129 feature:shared user append in child table notes field added
  startinsights/start_insights/doctype/shared_users/shared_users.json
  startinsights/website_api/pitch_room.py
Labels: enhancement

#130 feat:pitch room share room link details
  startinsights/website_api/pitch_room.py
Labels: enhancement

#131 bug-fix:pitch room shared user corrections
  startinsights/website_api/pitch_room.py
Labels: bug

#132 feature:pitch room doc upload correction
  startinsights/website_api/pitch_room.py
Labels: enhancement

#134 feat:pitch room documents upload changes
  startinsights/start_insights/doctype/pitch_craft_document_table/pitch_craft_document_table.json
  startinsights/website_api/pitch_room.py
Labels: enhancement

#136 feat:learn api
  startinsights/start_insights/custom/lms_course.json
  startinsights/start_insights/doctype/learn_favourites/__init__.py
  startinsights/start_insights/doctype/learn_favourites/learn_favourites.js
  startinsights/start_insights/doctype/learn_favourites/learn_favourites.json
  startinsights/start_insights/doctype/learn_favourites/learn_favourites.py
  startinsights/start_insights/doctype/learn_favourites/test_learn_favourites.py
  startinsights/website_api/lms_course.py
  startinsights/website_api/pitch_room.py
Labels: enhancement

#137 feat:learn doctype attach image added
  startinsights/start_insights/custom/lms_course.json
Labels: enhancement

#138 bug-fix:get favourite course object name changed
  startinsights/website_api/lms_course.py
Labels: bug

#139 bug-fix:favourite course key name changed as courses list
  startinsights/website_api/lms_course.py
Labels: bug

#140 feat:event api for both live and recorded event
  startinsights/start_insights/doctype/event_speakers_table/__init__.py
  startinsights/start_insights/doctype/event_speakers_table/event_speakers_table.json
  startinsights/start_insights/doctype/event_speakers_table/event_speakers_table.py
  startinsights/start_insights/doctype/registered_event/__init__.py
  startinsights/start_insights/doctype/registered_event/registered_event.js
  startinsights/start_insights/doctype/registered_event/registered_event.json
  startinsights/start_insights/doctype/registered_event/registered_event.py
  startinsights/start_insights/doctype/registered_event/test_registered_event.py
  startinsights/start_insights/doctype/si_events/__init__.py
  startinsights/start_insights/doctype/si_events/si_events.js
  startinsights/start_insights/doctype/si_events/si_events.json
  startinsights/start_insights/doctype/si_events/si_events.py
  startinsights/start_insights/doctype/si_events/test_si_events.py
  startinsights/website_api/event.py
Labels: enhancement

#141 bug-fix:get event local variable
  startinsights/website_api/event.py
Labels: bug

#142 feat:event fields and logics changes
  startinsights/start_insights/doctype/event_speakers_table/event_speakers_table.json
  startinsights/start_insights/doctype/si_events/si_events.js
  startinsights/start_insights/doctype/si_events/si_events.json
  startinsights/website_api/event.py
Labels: enhancement

#144 feat:pitch room edit room and update room
  startinsights/start_insights/doctype/pitch_room/pitch_room.json
  startinsights/start_insights/doctype/pitch_room_notes/__init__.py
  startinsights/start_insights/doctype/pitch_room_notes/pitch_room_notes.js
  startinsights/start_insights/doctype/pitch_room_notes/pitch_room_notes.json
  startinsights/start_insights/doctype/pitch_room_notes/pitch_room_notes.py
  startinsights/start_insights/doctype/pitch_room_notes/test_pitch_room_notes.py
  startinsights/website_api/pitch_room.py
Labels: enhancement

#145 feat:pitch room update changes
  startinsights/start_insights/doctype/pitch_craft_document_table/pitch_craft_document_table.json
  startinsights/website_api/pitch_room.py
  startinsights/website_api/profile.py
Labels: enhancement

#146 remove:pitch room get details particular room
  startinsights/website_api/pitch_room.py
Labels: enhancement

#147 feat:pitch room documents removed method
  startinsights/website_api/pitch_room.py
Labels: enhancement

#148 bug-fix:pitch room doc count zero remove
  startinsights/custom.py
  startinsights/website_api/pitch_room.py
Labels: bug

#149 feat:profile list view
  startinsights/website_api/captable_management.py
  startinsights/website_api/profile.py
Labels: enhancement

#150 bug-fix:captable management zero will be string
  startinsights/website_api/captable_management.py
Labels: bug

#151 bug-fix:captable list view round wise object bug fixed
  startinsights/website_api/captable_management.py
Labels: bug

#152 bug-fix:pitch room update docupload count local variable issue
  startinsights/website_api/pitch_room.py
Labels: bug

#153 bug-fix:profile list view none type empty string applied
  startinsights/website_api/profile.py
Labels: bug

#154 changes:profile list view dict key changes
  startinsights/website_api/profile.py
Labels: enhancement

#155 bug-fix:profile changes list view key fixed
  startinsights/website_api/profile.py
Labels: bug

#156 feat:add investors changes
  startinsights/start_insights/doctype/funding_crm/funding_crm.json
  startinsights/start_insights/doctype/search_investors_favourites/search_investors_favourites.py
  startinsights/start_insights/doctype/user_created_investors/user_created_investors.json
  startinsights/website_api/funding_crm.py
  startinsights/website_api/login.py
  startinsights/website_api/search_investors.py
  startinsights/website_api/user_creation_investor.py
Labels: enhancement

#157 feat:search investors
  startinsights/website_api/search_investors.py
Labels: enhancement

#158 feat:fundraising expert
  startinsights/custom.py
  startinsights/start_insights/doctype/fundraising_expert_table/__init__.py
  startinsights/start_insights/doctype/fundraising_expert_table/fundraising_expert_table.json
  startinsights/start_insights/doctype/fundraising_expert_table/fundraising_expert_table.py
  startinsights/start_insights/doctype/fundraising_experts/__init__.py
  startinsights/start_insights/doctype/fundraising_experts/fundraising_experts.js
  startinsights/start_insights/doctype/fundraising_experts/fundraising_experts.json
  startinsights/start_insights/doctype/fundraising_experts/fundraising_experts.py
  startinsights/start_insights/doctype/fundraising_experts/test_fundraising_experts.py
  startinsights/start_insights/doctype/service_listing/service_listing.json
  startinsights/website_api/book_an_expert.py
  startinsights/website_api/funding_crm.py
  startinsights/website_api/fundraising_experts.py
Labels: enhancement

#159 feat:my services user document upload method
  startinsights/start_insights/doctype/my_services/my_services.json
  startinsights/start_insights/doctype/process_steps/process_steps.json
  startinsights/start_insights/doctype/services_document_upload_table/__init__.py
  startinsights/start_insights/doctype/services_document_upload_table/services_document_upload_table.json
  startinsights/start_insights/doctype/services_document_upload_table/services_document_upload_table.py
  startinsights/website_api/services.py
Labels: enhancement

#160 feat:service tracking status
  startinsights/start_insights/doctype/my_service_deliverables/__init__.py
  startinsights/start_insights/doctype/my_service_deliverables/my_service_deliverables.json
  startinsights/start_insights/doctype/my_service_deliverables/my_service_deliverables.py
  startinsights/start_insights/doctype/my_services/my_services.json
  startinsights/website_api/services.py
Labels: enhancement

#161 feat:my services details
  startinsights/website_api/services.py
Labels: enhancement
